import { Category, Product, Sauce } from "@/types";

export const CATEGORIES: Category[] = [
    // Group 1: Appetizers/Rolls (No Header)
    { id: 'maki', name: 'Maki', slug: 'maki', group: 'main' },
    { id: 'rolinho', name: 'Rolinho primavera', slug: 'rolinho-primavera', group: 'main' },
    { id: 'doces', name: 'Pãezinhos Doces', slug: 'paezinhos-doces', group: 'main' },

    // Group 2: Sushi Types
    { id: 'sushi', name: 'Sushi', slug: 'sushi', group: 'Sushi, Sashimi, Gunkan' },
    { id: 'gunkan', name: 'Gunkan', slug: 'gunkan', group: 'Sushi, Sashimi, Gunkan' },
    { id: 'sashimi', name: 'Sashimi', slug: 'sashimi', group: 'Sushi, Sashimi, Gunkan' },
    { id: 'temaki', name: 'Temaki', slug: 'temaki', group: 'Sushi, Sashimi, Gunkan' },

    // Group 3: Hot Dishes
    { id: 'sopa', name: 'Sopa', slug: 'sopa', group: 'Pratos' },
    { id: 'arroz', name: 'Arroz', slug: 'arroz', group: 'Pratos' },
    { id: 'wok', name: 'Wok', slug: 'wok', group: 'Pratos' },
    { id: 'ramen', name: 'Ramen', slug: 'ramen', group: 'Pratos' },
    { id: 'yaki', name: 'Grelhados', slug: 'grelhados', group: 'Pratos' },
    { id: 'poke', name: 'Poke', slug: 'poke', group: 'Pratos' },

    // Group 4: Drinks
    { id: 'bebida', name: 'Drink', slug: 'bebida', group: 'Bebida', isHighlight: true },

    // Group 5: Sauces
    { id: 'molhos', name: 'Molhos', slug: 'molhos', group: 'Molhos', isHeaderOnly: true } // Assuming it acts as header or category
];

export const SAUCES: Sauce[] = [
    { id: '1', name: 'Maionese Picante', price: 300, image: '/images/sauce-spicy.png' },
    { id: '2', name: 'Teriyaki', price: 300, image: '/images/sauce-teriyaki.png' },
    { id: '3', name: 'Wasabi', price: 0, image: '/images/sauce-wasabi.png' }, // Free? or 300
    { id: '4', name: 'Gengibre', price: 0, image: '/images/sauce-ginger.png' },
];


export const PRODUCTS: Product[] = [
    // --- Maki ---
    {
        id: 'm1',
        name: 'Tekka Maki',
        slug: 'tekka-maki',
        description: 'Clássico rolinho de atum fresco envolto em nori.',
        price: 650,
        image: '/images/Tuna-sashimi.jpeg',
        categoryId: 'maki',
        ingredients: 'Atum, Nori, Arroz de Sushi',
        relatedProductIds: ['s1', 's2'],
    },
    {
        id: 'm2',
        name: 'Kappa Maki',
        slug: 'kappa-maki',
        description: 'Refrescante rolinho de pepino com sementes de gergelim.',
        price: 450,
        image: '/images/California-roll.jpeg',
        categoryId: 'maki',
        ingredients: 'Pepino, Sementes de Gergelim, Nori, Arroz',
        relatedProductIds: ['m1', 's1'],
    },
    {
        id: 'm3',
        name: 'Spicy Salmon Maki',
        slug: 'spicy-salmon-maki',
        description: 'Salmão com maionese picante e pepino.',
        price: 750,
        image: '/images/Salmon-nigiri.jpeg',
        categoryId: 'maki',
        isPopular: true,
        ingredients: 'Salmão, Maionese Picante, Pepino, Nori',
        relatedProductIds: ['m1', 's2'],
    },
    {
        id: 'roll1',
        name: 'Dragon Roll',
        slug: 'dragon-roll',
        description: 'Enguia e pepino cobertos com abacate e molho unagi.',
        price: 1400,
        image: '/images/Dragon-roll.jpeg',
        categoryId: 'maki',
        isPopular: true,
        ingredients: 'Enguia, Pepino, Abacate, Molho Unagi',
        relatedProductIds: ['roll2'],
    },
    {
        id: 'roll2',
        name: 'California Roll',
        slug: 'california-roll',
        description: 'Kani, pepino e abacate.',
        price: 850,
        image: '/images/California-roll.jpeg',
        categoryId: 'maki',
        ingredients: 'Kani, Pepino, Abacate, Gergelim',
        relatedProductIds: ['roll1'],
    },
    {
        id: 'roll3',
        name: 'Hot Philadelphia',
        slug: 'hot-philadelphia',
        description: 'Rolinho frito com salmão e cream cheese.',
        price: 1800,
        image: '/images/Hot-philadelphia.jpeg',
        categoryId: 'maki',
        isPopular: true,
        ingredients: 'Salmão, Cream Cheese, Panko, Teriyaki',
        relatedProductIds: ['roll1', 'soup1'],
    },

    // --- Rolinho Primavera ---
    {
        id: 'r1',
        name: 'Harumaki de Legumes',
        slug: 'harumaki-legumes',
        description: 'Rolinhos primavera crocantes recheados com legumes temperados (2 unidades).',
        price: 500,
        image: '/images/spring-rolls.png',
        categoryId: 'rolinho',
        ingredients: 'Repolho, Cenoura, Macarrão de Vidro, Massa de Harumaki',
        relatedProductIds: ['r2', 'd1'],
    },
    {
        id: 'r2',
        name: 'Harumaki de Camarão',
        slug: 'harumaki-camarao',
        description: 'Rolinhos primavera de camarão premium servidos com molho de pimenta doce.',
        price: 700,
        image: '/images/spring-rolls.png',
        categoryId: 'rolinho',
        isPopular: true,
        ingredients: 'Camarão, Alho, Coentro, Massa',
        relatedProductIds: ['r1', 'w1'],
    },

    // --- Pãezinhos doces ---
    {
        id: 'pd1',
        name: 'Manju de Feijão Doce',
        slug: 'manju',
        description: 'Pão tradicional no vapor com pasta de feijão vermelho doce.',
        price: 400,
        image: '/images/ebi-nigiri.png',
        categoryId: 'doces',
        ingredients: 'Farinha, Pasta de Feijão Vermelho, Açúcar',
        relatedProductIds: ['d2'],
    },

    // --- Sushi ---
    {
        id: 's1',
        name: 'Nigiri de Salmão',
        slug: 'salmon-nigiri',
        description: 'Salmão fresco do Atlântico sobre arroz temperado. Simples e clássico.',
        price: 900,
        image: '/images/Salmon-nigiri.jpeg',
        categoryId: 'sushi',
        isPopular: true,
        ingredients: 'Arroz de Sushi, Salmão Fresco, Wasabi (Opcional)',
        relatedProductIds: ['s2', 's3', 'g1'],
    },
    {
        id: 's2',
        name: 'Nigiri de Atum',
        slug: 'tuna-nigiri',
        description: 'Sushi moldado à mão com fatia de atum fresco.',
        price: 1100,
        image: '/images/Tuna-sashimi.jpeg',
        categoryId: 'sushi',
        ingredients: 'Arroz de Sushi, Atum, Wasabi',
        relatedProductIds: ['s1', 'g1'],
    },
    {
        id: 's3',
        name: 'Nigiri de Ebi',
        slug: 'ebi-nigiri',
        description: 'Sushi clássico de camarão cozido (2 unidades).',
        price: 1100,
        image: '/images/ebi-nigiri.png',
        categoryId: 'sushi',
        ingredients: 'Camarão Cozido, Arroz de Sushi, Wasabi (Opcional)',
        relatedProductIds: ['s1', 'm3'],
    },
    {
        id: 's4',
        name: 'Nigiri de Salmão com Trufas',
        slug: 'truffle-salmon',
        description: 'Nigiri de salmão com raspas de trufa negra e caviar (2 unidades).',
        price: 3200,
        image: '/images/Truffle-Salmon-Nigiri.jpeg',
        categoryId: 'sushi',
        isPopular: true,
        isNew: true,
        ingredients: 'Salmão, Trufa Negra, Caviar, Arroz de Sushi',
        relatedProductIds: ['g1', 'w1'],
    },
    {
        id: 'combo1',
        name: 'Combo Especial Saitama',
        slug: 'saitama-special',
        description: 'Seleção do Chef de 12 peças, incluindo cortes premium.',
        price: 4500,
        image: '/images/Saitama-Special-Combo.jpeg',
        categoryId: 'sushi',
        isNew: true,
        isPopular: true,
        ingredients: 'Seleção do Chef: Salmão, Atum, Hamachi, Vieira, Wagyu, Uni',
        relatedProductIds: ['s1', 's2', 's3'],
    },

    // --- Gunkan ---
    {
        id: 'g1',
        name: 'Gunkan de Uni',
        slug: 'uni-gunkan',
        description: 'Ouriço-do-mar fresco de Hokkaido (2 unidades).',
        price: 4800,
        image: '/images/Gunkan-union.jpeg',
        categoryId: 'gunkan',
        isPopular: true,
        ingredients: 'Uni de Hokkaido (Ouriço-do-mar), Nori, Arroz de Sushi',
        relatedProductIds: ['s4', 'sa1'],
    },
    {
        id: 'g2',
        name: 'Gunkan de Ikura',
        slug: 'ikura-gunkan',
        description: 'Sushi em formato de barco com ovas de salmão marinadas.',
        price: 2200,
        image: '/images/Gunkan-union.jpeg',
        categoryId: 'gunkan',
        ingredients: 'Ovas de Salmão, Pepino, Nori, Arroz',
        relatedProductIds: ['g1', 's1'],
    },

    // --- Sashimi ---
    {
        id: 'sa1',
        name: 'Sashimi de Atum',
        slug: 'tuna-sashimi',
        description: 'Fatias de atum premium (3 unidades).',
        price: 1200,
        image: '/images/Tuna-sashimi.jpeg',
        categoryId: 'sashimi',
        ingredients: 'Fatias de Atum Premium, Nabo Daikon, Folha de Shiso',
        relatedProductIds: ['s1', 'm1'],
    },
    {
        id: 'sa2',
        name: 'Sashimi de Salmão',
        slug: 'salmon-sashimi',
        description: 'Fatias grossas de salmão fresco do Atlântico (3 unidades).',
        price: 1100,
        image: '/images/salmon-sashimi.jpeg',
        categoryId: 'sashimi',
        ingredients: 'Salmão Fresco, Wasabi',
        relatedProductIds: ['sa1', 's1'],
    },

    // --- Temaki ---
    {
        id: 'tm1',
        name: 'Temaki Saitama',
        slug: 'temaki-saitama',
        description: 'Cone de mão com salmão fresco, abacate e pepino.',
        price: 1800,
        image: '/images/temaki-saitama.jpeg',
        categoryId: 'temaki',
        isPopular: true,
        ingredients: 'Salmão, Abacate, Pepino, Nori, Arroz de Sushi, Gergelim',
        relatedProductIds: ['s1', 'm3'],
    },
    {
        id: 'tm2',
        name: 'Temaki Frito',
        slug: 'temaki-frito',
        description: 'Temaki frito crocante com cream cheese e salmão.',
        price: 2200,
        image: '/images/temaki-frito.jpeg',
        categoryId: 'temaki',
        isPopular: true,
        isNew: true,
        ingredients: 'Salmão, Cream Cheese, Panko, Nori, Arroz, Molho Sweet Chili',
        relatedProductIds: ['tm1', 'roll3'],
    },

    // --- Hot Dishes (Pratos) ---
    {
        id: 'soup1',
        name: 'Sopa de Missô',
        slug: 'miso-soup',
        description: 'Sopa tradicional de pasta de soja com tofu e wakame.',
        price: 350,
        image: '/images/Tempura-udon.jpeg',
        categoryId: 'sopa',
        ingredients: 'Pasta de Missô, Dashi, Tofu, Cebolinha, Wakame',
        relatedProductIds: ['arroz1'],
    },
    {
        id: 'arroz1',
        name: 'Gohan',
        slug: 'gohan',
        description: 'Arroz japonês de grão curto premium cozido no vapor.',
        price: 300,
        image: '/images/gohan.jpeg',
        categoryId: 'arroz',
        ingredients: 'Arroz, Sementes de Gergelim',
        relatedProductIds: ['soup1'],
    },

    // --- WOK ---
    {
        id: 'wok1',
        name: 'Wok com Frango',
        slug: 'wok-chicken',
        description: 'Macarrão frito com frango e legumes.',
        price: 2400,
        image: '/images/Pasta_with_chicken_202512112122.jpeg',
        categoryId: 'wok',
        ingredients: 'Macarrão, Peito de Frango, Repolho, Cenoura, Cebola, Molho Yakisoba',
        relatedProductIds: ['r1', 'd1'],
    },
    {
        id: 'wok2',
        name: 'Wok com Carne',
        slug: 'wok-beef',
        description: 'Macarrão frito com tiras de carne e legumes.',
        price: 2600,
        image: '/images/Pasta_and_meat_202512112124.jpeg',
        categoryId: 'wok',
        ingredients: 'Macarrão, Tiras de Carne, Repolho, Cenoura, Molho Especial',
        relatedProductIds: ['wok1', 'd1'],
    },
    {
        id: 'wok3',
        name: 'Wok com Frutos do Mar',
        slug: 'wok-seafood',
        description: 'Macarrão frito com frutos do mar, camarão e lula.',
        price: 3000,
        image: '/images/Pasta_and_seafood_202512112124.jpeg',
        categoryId: 'wok',
        isPopular: true,
        ingredients: 'Macarrão, Camarão, Lula, Legumes, Molho de Soja para Frutos do Mar',
        relatedProductIds: ['wok2', 'd2'],
    },
    {
        id: 'wok4',
        name: 'Wok Vegetariano (Cabelo de Anjo)',
        slug: 'wok-angel-hair',
        description: 'Massa delicada cabelo de anjo frita com legumes da estação.',
        price: 2200,
        image: '/images/Angel_hair_pasta_202512112123.jpeg',
        categoryId: 'wok',
        ingredients: 'Macarrão Cabelo de Anjo, Legumes Mistos, Molho de Soja Leve',
        relatedProductIds: ['r1', 'soup1'],
    },

    // --- Ramen ---
    {
        id: 'ramen1',
        name: 'Ramen de Carne',
        slug: 'ramen-beef',
        description: 'Ramen com caldo de carne rico e fatias macias.',
        price: 3200,
        image: '/images/Meat_ramen_202512112137.jpeg',
        categoryId: 'ramen',
        ingredients: 'Macarrão Ramen, Caldo de Carne, Carne Fatiada, Ovo, Nori, Cebolinha',
        relatedProductIds: ['wok2'],
    },
    {
        id: 'ramen2',
        name: 'Ramen com Milanesa',
        slug: 'ramen-breaded',
        description: 'Ramen coberto com costeleta empanada crocante (katsu).',
        price: 3400,
        image: '/images/Ramen_with_breaded_202512112138.jpeg',
        categoryId: 'ramen',
        isPopular: true,
        ingredients: 'Macarrão Ramen, Caldo Tonkotsu, Costeleta Empanada, Milho, Brotos de Bambu',
        relatedProductIds: ['wok1'],
    },
    {
        id: 'ramen3',
        name: 'Ramen de Porco (Chashu)',
        slug: 'ramen-pork',
        description: 'Ramen clássico com barriga de porco braseada.',
        price: 3000,
        image: '/images/Ramen_with_pork_202512112136.jpeg',
        categoryId: 'ramen',
        isPopular: true,
        ingredients: 'Macarrão Ramen, Caldo de Porco, Porco Chashu, Ovo, Narutomaki',
        relatedProductIds: ['ramen1'],
    },
    {
        id: 'ramen4',
        name: 'Ramen de Frutos do Mar',
        slug: 'ramen-seafood',
        description: 'Ramen de frutos do mar com camarão e lula em caldo claro.',
        price: 3600,
        image: '/images/Seafood_ramen_202512112138.jpeg',
        categoryId: 'ramen',
        ingredients: 'Macarrão Ramen, Caldo Claro, Camarão, Lula, Mexilhões, Algas',
        relatedProductIds: ['wok3'],
    },
    {
        id: 'ramen5',
        name: 'Ramen de Frango',
        slug: 'ramen-chicken',
        description: 'Ramen com caldo leve de frango e frango grelhado.',
        price: 2800,
        image: '/images/ramem-de-frango.jpeg',
        categoryId: 'ramen',
        ingredients: 'Macarrão Ramen, Caldo de Frango, Frango Grelhado, Ovo, Milho',
        relatedProductIds: ['wok1'],
    },

    // --- Grelhados (Yaki) ---
    {
        id: 'yaki1',
        name: 'Wagyu Beef Roll (Yaki)',
        slug: 'wagyu-roll',
        description: 'Carne Wagyu A5 selada coberta com folha de ouro e azeite de trufas.',
        price: 8500,
        image: '/images/Wagyu-beef-roll.jpeg',
        categoryId: 'yaki',
        isPopular: true,
        ingredients: 'Carne Wagyu A5, Azeite de Trufas, Folha de Ouro, Aspargos',
        relatedProductIds: ['s4', 'g1'],
    },
    {
        id: 'yaki2',
        name: 'Filet Mignon Grelhado',
        slug: 'filet-mignon-grelhado',
        description: 'Filé mignon grelhado macio servido com legumes.',
        price: 5500,
        image: '/images/Carne-file-mingno-grelhado.jpeg',
        categoryId: 'yaki',
        isPopular: true,
        ingredients: 'Filé Mignon, Legumes da Estação, Manteiga de Alho',
        relatedProductIds: ['yaki1', 'arroz1'],
    },
    {
        id: 'yaki3',
        name: 'Salmão Grelhado',
        slug: 'salmao-grelhado',
        description: 'Filé de salmão perfeitamente grelhado com pele crocante.',
        price: 4200,
        image: '/images/Salmao-grelhado.jpeg',
        categoryId: 'yaki',
        ingredients: 'Salmão Fresco, Limão, Sal Marinho, Aspargos',
        relatedProductIds: ['rice2', 'sopa'],
    },
    {
        id: 'yaki4',
        name: 'Camarão Grelhado',
        slug: 'camarao-grelhado',
        description: 'Camarões grandes grelhados com alho e ervas.',
        price: 4800,
        image: '/images/camarao-grelhado.jpeg',
        categoryId: 'yaki',
        ingredients: 'Camarão Jumbo, Alho, Salsa, Azeite de Oliva',
        relatedProductIds: ['rice4', 's3'],
    },
    {
        id: 'yaki5',
        name: 'Enguia Grelhada (Unagi)',
        slug: 'enguia-grelhada',
        description: 'Enguia de água doce grelhada tradicional com cobertura de soja doce.',
        price: 6000,
        image: '/images/enguia-grelhado.jpeg',
        categoryId: 'yaki',
        isPopular: true,
        ingredients: 'Enguia (Unagi), Molho Unagi, Sementes de Gergelim',
        relatedProductIds: ['arroz1', 'sopa'],
    },
    {
        id: 'yaki6',
        name: 'Atum Selado Grelhado',
        slug: 'atum-grelhado',
        description: 'Steak de atum selado com crosta de gergelim.',
        price: 4500,
        image: '/images/grelhado-atum.jpeg',
        categoryId: 'yaki',
        ingredients: 'Steak de Atum, Sementes de Gergelim, Molho Ponzu, Gengibre',
        relatedProductIds: ['sa1', 's2'],
    },

    {
        id: 'poke1',
        name: 'Poke de Salmão',
        slug: 'poke-salmon',
        description: 'Tigela de arroz de sushi coberta com cubos de salmão fresco e legumes.',
        price: 3200,
        image: '/images/Rice_with_salmon_202512112115.jpeg',
        categoryId: 'poke',
        isPopular: true,
        ingredients: 'Salmão, Abacate, Edamame, Arroz, Molho Poke, Gergelim',
        relatedProductIds: ['poke2', 's1'],
    },
    {
        id: 'poke2',
        name: 'Poke de Atum',
        slug: 'poke-tuna',
        description: 'Tigela de poke de atum fresco com abacate e cebola crocante.',
        price: 3400,
        image: '/images/poke-de-atum.jpeg',
        categoryId: 'poke',
        isPopular: true,
        ingredients: 'Atum, Abacate, Edamame, Pepino, Arroz, Molho Poke',
        relatedProductIds: ['poke1', 's2'],
    },
    {
        id: 'poke3',
        name: 'Poke de Camarão',
        slug: 'poke-shrimp',
        description: 'Poke de camarão suculento com manga e folhas frescas.',
        price: 3600,
        image: '/images/poke-de-camarao.jpeg',
        categoryId: 'poke',
        ingredients: 'Camarão, Manga, Pepino, Arroz, Gergelim, Maionese Picante',
        relatedProductIds: ['poke1', 'poke2'],
    },
    {
        id: 'poke4',
        name: 'Poke de Frango',
        slug: 'poke-chicken',
        description: 'Tigela de poke de frango grelhado com cobertura de teriyaki.',
        price: 2800,
        image: '/images/poke-de-frango.jpeg',
        categoryId: 'poke',
        ingredients: 'Frango Grelhado, Molho Teriyaki, Legumes, Arroz, Gergelim',
        relatedProductIds: ['poke1', 'wok1'],
    },
    {
        id: 'poke5',
        name: 'Poke de Legumes',
        slug: 'poke-veggies',
        description: 'Tigela de poke vegetariano com tofu e legumes da estação.',
        price: 2600,
        image: '/images/poke-de-legumes.jpg',
        categoryId: 'poke',
        ingredients: 'Tofu, Edamame, Pepino, Cenoura, Abacate, Arroz, Gergelim',
        relatedProductIds: ['poke1', 'rice1'],
    },

    // --- Drinks ---
    {
        id: 'd1',
        name: 'Coca-Cola Zero',
        slug: 'coke-zero',
        description: 'Lata 350ml.',
        price: 350,
        image: '/images/coca-cola.jpg',
        categoryId: 'bebida',
        ingredients: 'Água Gaseificada, Corante Caramelo, Aspartame',
        relatedProductIds: [],
    },
    {
        id: 'd2',
        name: 'Chá Verde',
        slug: 'green-tea',
        description: 'Chá verde gelado japonês feito na hora.',
        price: 400,
        image: '/images/green-tea.jpg',
        categoryId: 'bebida',
        ingredients: 'Chá Verde, Água',
        relatedProductIds: [],
    },
    {
        id: 'd3',
        name: 'Caipirinha',
        slug: 'caipirinha',
        description: 'Coquetel brasileiro clássico com cachaça e limão.',
        price: 1800,
        image: '/images/Caipirinha.jpg',
        categoryId: 'bebida',
        isPopular: true,
        ingredients: 'Cachaça, Limão, Açúcar, Gelo',
        relatedProductIds: [],
    },
    {
        id: 'd4',
        name: 'Cosmopolitan',
        slug: 'cosmopolitan',
        description: 'Coquetel à base de vodka com cranberry e triple sec.',
        price: 2200,
        image: '/images/Cosmopolitan Cocktail.jpg',
        categoryId: 'bebida',
        ingredients: 'Vodka, Triple Sec, Suco de Cranberry, Suco de Limão',
        relatedProductIds: [],
    },
    {
        id: 'd5',
        name: 'Moscow Mule',
        slug: 'moscow-mule',
        description: 'Coquetel de vodka com cerveja de gengibre e limão.',
        price: 2400,
        image: '/images/Moscow Mule.jpg',
        categoryId: 'bebida',
        isPopular: true,
        ingredients: 'Vodka, Cerveja de Gengibre, Suco de Limão',
        relatedProductIds: [],
    },
    {
        id: 'd6',
        name: 'Orange Drink',
        slug: 'orange-drink',
        description: 'Bebida de laranja gaseificada refrescante.',
        price: 1500,
        image: '/images/Orange drink.jpg',
        categoryId: 'bebida',
        ingredients: 'Suco de Laranja, Água com Gás, Hortelã',
        relatedProductIds: [],
    },
    {
        id: 'd7',
        name: 'Pink Cocktail',
        slug: 'pink-cocktail',
        description: 'Coquetel doce e frutado com infusão de frutas vermelhas.',
        price: 2100,
        image: '/images/Pink Cocktail.jpg',
        categoryId: 'bebida',
        ingredients: 'Gin, Frutas Vermelhas Mistas, Limão, Água com Gás',
        relatedProductIds: [],
    },
    {
        id: 'd8',
        name: 'Spicy Fall Margarita',
        slug: 'spicy-margarita',
        description: 'Coquetel de tequila com pimenta e especiarias de outono.',
        price: 2600,
        image: '/images/spicy fall margarita.jpg',
        categoryId: 'bebida',
        ingredients: 'Tequila, Limão, Pimenta, Canela, Agave',
        relatedProductIds: [],
    },

    // --- Rice (from Image) ---
    {
        id: 'rice1',
        name: 'Arroz com Legumes',
        slug: 'rice-veggies',
        description: 'Arroz frito com legumes mistos da estação.',
        price: 1600,
        image: '/images/arroz-com-legumes.jpeg',
        categoryId: 'arroz',
        ingredients: 'Arroz, Cenoura, Ervilha, Milho, Molho de Soja, Óleo de Gergelim',
        relatedProductIds: ['soup1', 'd2'],
    },
    {
        id: 'rice2',
        name: 'Arroz com Salmão',
        slug: 'rice-salmon',
        description: 'Arroz frito coberto com pedaços de salmão fresco.',
        price: 4400,
        image: '/images/Rice_with_salmon_202512112115.jpeg',
        categoryId: 'arroz',
        isPopular: true,
        ingredients: 'Arroz, Salmão, Ovo, Cebolinha, Molho de Soja',
        relatedProductIds: ['s1', 'soup1'],
    },
    {
        id: 'rice3',
        name: 'Arroz com Frutos do Mar',
        slug: 'rice-seafood',
        description: 'Arroz frito de luxo com frutos do mar mistos e legumes.',
        price: 4300,
        image: '/images/Rice_with_seafood_202512112116.jpeg',
        categoryId: 'arroz',
        ingredients: 'Arroz, Camarão, Lula, Mexilhões, Legumes',
        relatedProductIds: ['rice2', 'd1'],
    },
    {
        id: 'rice4',
        name: 'Arroz com Camarão',
        slug: 'rice-shrimp',
        description: 'Arroz frito com camarão suculento e legumes.',
        price: 4000,
        image: '/images/Rice_with_camarao_202512112117.jpeg',
        categoryId: 'arroz',
        isPopular: true,
        ingredients: 'Arroz, Camarão, Legumes, Ovo, Molho de Soja',
        relatedProductIds: ['rice3', 'r2'],
    },
    {
        id: 'rice5',
        name: 'Arroz com Carne',
        slug: 'rice-beef',
        description: 'Arroz frito farto com tiras de carne macia.',
        price: 2800,
        image: '/images/Rice_with_meat_202512112118.jpeg',
        categoryId: 'arroz',
        ingredients: 'Arroz, Tiras de Carne, Cebola, Alho, Molho de Soja',
        relatedProductIds: ['rice1', 'd1'],
    },
    {
        id: 'rice6',
        name: 'Arroz com Frango',
        slug: 'rice-chicken',
        description: 'Arroz frito clássico com peito de frango.',
        price: 2400,
        image: '/images/Now_recreate_the_202512112114.jpeg',
        categoryId: 'arroz',
        ingredients: 'Arroz, Peito de Frango, Ovo, Ervilha, Cenoura',
        relatedProductIds: ['rice1', 'd2'],
    },
    {
        id: 'rice7',
        name: 'Arroz com Frango Picante',
        slug: 'rice-spicy-chicken',
        description: 'Arroz frito de frango picante com óleo de pimenta.',
        price: 2600,
        image: '/images/Spicy_chicken_and_202512112120.jpeg',
        categoryId: 'arroz',
        ingredients: 'Arroz, Frango, Óleo de Pimenta, Alho, Cebolinha',
        relatedProductIds: ['d1', 'r1'],
    },
    {
        id: 'rice8',
        name: 'Arroz com Polvo',
        slug: 'rice-octopus',
        description: 'Arroz frito com pedaços macios de polvo.',
        price: 3000,
        image: '/images/Rice_with_octopus_202512112120.jpeg',
        categoryId: 'arroz',
        ingredients: 'Arroz, Polvo, Legumes, Alga Marinha',
        relatedProductIds: ['rice3', 's3'],
    },
];
